CREATE DATABASE MySweetyDB2
COLLATE Cyrillic_General_CI_AS;
USE MySweetyDB2

CREATE TABLE Trader /*OK*/   
(
	ID INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(40) NOT NULL,
	Adress NVARCHAR(40) NOT NULL ,
	Tel NVARCHAR(10) NOT NULL,
	Tax_Number  BIGINT UNIQUE CHECK(LEN(Tax_Number) BETWEEN 9 AND 13) NOT NULL,
	MOL NVARCHAR(40)
	CONSTRAINT	Trader_PK PRIMARY KEY (ID)
);

CREATE TABLE Material /*OK*/
(
	ID INT NOT NULL IDENTITY(1,1),
	Material NVARCHAR(40) NOT NULL,
	CONSTRAINT	Material_PK PRIMARY KEY (ID)
);

CREATE TABLE Goods /*OK*/
(
	ID INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(40) NOT NULL,
	MaterialID INT NOT NULL ,
	RetailPrice MONEY NOT NULL,
	CONSTRAINT	Goods_PK PRIMARY KEY (Id),
	CONSTRAINT FK_Goods_Material FOREIGN KEY (MaterialID) REFERENCES Material (ID)
);

CREATE TABLE Invoice  /*OK*/
(
	ID INT NOT NULL IDENTITY(1,1),
	Date /*На издаване*/ DATE NOT NULL,
	TraderID INT NOT NULL
	CONSTRAINT	Invoice_PK PRIMARY KEY (ID),
	CONSTRAINT FK_Invoice_Trader FOREIGN KEY (TraderID) REFERENCES Trader (ID)
);

CREATE TABLE Orders
(
	ID INT NOT NULL IDENTITY(1,1),
	GoodID INT NOT NULL,
	Quantity INT NOT NULL,
	InvoiceID INT NOT NULL,
	CONSTRAINT	Factur_PK PRIMARY KEY (ID),
	CONSTRAINT FK_Orders_Goods FOREIGN KEY (GoodID) REFERENCES Goods (ID),
	CONSTRAINT FK_Orders_Invoice FOREIGN KEY (InvoiceID) REFERENCES Invoice (ID)
);

